/**
 * The "Edi Guide" help document. Opened in a tab from the Help menu, covering
 * the features that make Edi different from a plain markdown editor. Kept as a
 * single source string so the guide can never drift from a separate doc.
 */
export function buildHelpGuideMarkdown(): string {
  return [
    '# Edi Guide',
    '',
    'Edi is a fast markdown editor in a desktop window. Markdown is the source;',
    'the preview renders it live — and a few block types go much further.',
    '',
    '## Tabs, menus, and shortcuts',
    '',
    '- Documents open in tabs: `Ctrl+N` new, `Ctrl+W` close, `Ctrl+O` open,',
    '  `Ctrl+S` save, `Ctrl+Shift+S` save as, `Ctrl+Q` quit.',
    '- File actions also live as toolbar buttons; hide that row with',
    '  `View → Toolbar`.',
    '- Click the small handle on a block\'s left edge to toggle its source view.',
    '',
    '## Spreadsheet tables',
    '',
    '`Insert → Table…` (or the toolbar\'s **Table** button) drops a spreadsheet',
    'grid into the document; `Insert → Spreadsheet…` imports a CSV/TSV/ODS/XLSX',
    'file as a table.',
    '',
    'A cell whose text starts with `=` is a formula:',
    '',
    '- References (`B2`, or freeze an axis with `$` — `$B$2`) and ranges',
    '  (`B2:C4`)',
    '- Functions such as `SUM`, `AVERAGE`, `IF`, `VLOOKUP`, `TODAY`, or `UUID` —',
    '  the `fx` bar above the grid edits the active cell and autocompletes names',
    '- Values recompute live; `Help → Formula Reference…` lists every function',
    '',
    '**Use values** freezes the selected cells\' formulas to their computed',
    'values (handy for volatile cells like `RAND`/`UUID`). **Resolve formulas?**',
    'does the same for the whole table: each value is stored in the cell with the',
    'formula kept in a comment and restored when the document reopens.',
    '',
    'Wrap a formula in inline marks to style the result without breaking the',
    'calculation: `**=SUM(B2:B3)**`, `*…*`, `` `…` ``, `==…==`, `~…~`, `^…^`.',
    '',
    '## Defining your own functions',
    '',
    'A fenced code block tagged `edi-formula` defines document-wide functions,',
    'one per line:',
    '',
    '````',
    '```edi-formula',
    'TAX(amount) = ROUND(amount * 0.2, 2)',
    '```',
    '````',
    '',
    'Call them like any built-in: `=TAX(B2)`. A parameter can be a number, a',
    'cell, or a range (delivered to `SUM`/`AVERAGE`/… as its values). Names may',
    'not collide with built-ins, repeat, or form a loop.',
    '',
    '## Masked fields',
    '',
    'The toolbar\'s **Insert encrypted field** stores a value as ciphertext — the',
    'markdown holds only `!masked[…]{label="…"}`, rendered as a masked pill.',
    'Click a pill to reveal, copy, or edit it (single password prompt per',
    'session), and the plaintext never appears in the document source.',
    '',
    '## Mermaid diagrams',
    '',
    'A fenced code block tagged `mermaid` renders as a diagram in the preview.',
    'Right-click the diagram for Copy as image / Save as image.',
    '',
    '## Runnable code blocks',
    '',
    'A fenced code block whose first line is a shebang becomes runnable:',
    '',
    '````',
    '```python',
    '#!/usr/bin/env python3',
    'print("Hello from Edi!")',
    '```',
    '````',
    '',
    'The preview shows a **Run** button; output lands beneath the block and',
    '**Stop** cancels a hung run.',
    '',
    '## Export',
    '',
    '`Ctrl+Shift+E` exports the rendered preview — Mermaid diagrams, computed',
    'spreadsheet values, and code output included — as one self-contained HTML',
    'file you can share or archive.',
    '',
  ].join('\n')
}