/**
 * The "Edi Guide" help document. Opened in a tab from the Help menu, covering
 * the features that make Edi different from a plain markdown editor. Kept as a
 * single source string so the guide can never drift from a separate doc.
 */
export function buildHelpGuideMarkdown(): string {
  return [
    '# Edi Guide',
    '',
    'Edi is a fast markdown editor in a desktop window. Markdown is the source;',
    'the preview renders it live — and a few block types go much further.',
    '',
    '## Tabs, menus, and shortcuts',
    '',
    '- Documents open in tabs: `Ctrl+N` new, `Ctrl+W` close, `Ctrl+O` open,',
    '  `Ctrl+S` save, `Ctrl+Shift+S` save as, `Ctrl+Q` quit.',
    '- File actions also live as toolbar buttons; hide that row with',
    '  `View → Toolbar`.',
    '- Click the small handle on a block\'s left edge to toggle its source view.',
    '',
    '## Spreadsheet tables',
    '',
    '`Insert → Table…` (or the toolbar\'s **Table** button) drops a spreadsheet',
    'grid into the document; `Insert → Spreadsheet…` imports a CSV/TSV/ODS/XLSX',
    'file as a table.',
    '',
    'A cell whose text starts with `=` is a formula:',
    '',
    '- References (`B2`, or freeze an axis with `$` — `$B$2`) and ranges',
    '  (`B2:C4`)',
    '- Functions such as `SUM`, `AVERAGE`, `IF`, `VLOOKUP`, `TODAY`, or `UUID` —',
    '  the `fx` bar above the grid edits the active cell and autocompletes names',
    '- Values recompute live; `Help → Formula Reference…` lists every function',
    '',
    '**Use values** freezes the selected cells\' formulas to their computed',
    'values (handy for volatile cells like `RAND`/`UUID`). **Resolve formulas?**',
    'does the same for the whole table: each value is stored in the cell with the',
    'formula kept in a comment and restored when the document reopens.',
    '',
    'Right-click a cell for undo/redo, cut, copy, paste, select all, clear',
    'contents, and inserting a row above or a column left; the block\'s',
    '`Table view` and `Edit source` sit below them. A right-click inside the',
    'current selection keeps it, and a column letter or row number offers to',
    'delete that column or row.',
    '',
    'Wrap a formula in inline marks to style the result without breaking the',
    'calculation: `**=SUM(B2:B3)**`, `*…*`, `` `…` ``, `==…==`, `~…~`, `^…^`.',
    '',
    '## Defining your own functions',
    '',
    'A fenced code block tagged `edi-formula` defines document-wide functions,',
    'one per line:',
    '',
    '````',
    '```edi-formula',
    'TAX(amount) = ROUND(amount * 0.2, 2)',
    '```',
    '````',
    '',
    'Call them like any built-in: `=TAX(B2)`. A parameter can be a number, a',
    'cell, or a range (delivered to `SUM`/`AVERAGE`/… as its values). Names may',
    'not collide with built-ins, repeat, or form a loop.',
    '',
    '## Masked fields',
    '',
    'The toolbar\'s **Insert encrypted field** stores a value as ciphertext — the',
    'markdown holds only `!masked[…]{label="…"}`, rendered as a masked pill.',
    'Click a pill to reveal, copy, or edit it (single password prompt per',
    'session), and the plaintext never appears in the document source.',
    '',
    '## Mermaid diagrams',
    '',
    'A fenced code block tagged `mermaid` renders as a diagram in the preview.',
    '',
    'To edit the picture, press **Edit** on the diagram\'s hover toolbar or',
    'double-click it; the right-click menu has **Edit diagram** too. The button',
    'reads **Done** while you are in edit mode, and only one diagram is editable',
    'at a time.',
    '',
    'Click a label to retype it — the source is patched in place. `Enter` or a',
    'click elsewhere commits, `Esc` cancels. In a **kanban** diagram, every',
    'column has a **+** that adds a card to it, and cards can be dragged between',
    'columns or up and down a column to reorder them.',
    '',
    'Only labels that can be rewritten are clickable. Anything Mermaid computed',
    'rather than read — a treemap\'s totals, a packet field\'s bit range, an xy',
    'chart\'s axis ticks, a card\'s assignee, a stereotype — stays put, and so',
    'does a label the source repeats with no way to tell the copies apart.',
    'Renaming a name the diagram uses elsewhere (an ER entity, a state, a class,',
    'a branch, a requirement) renames the references with it.',
    '',
    'The source is always the document: open the block with its handle to edit',
    'it as text. A diagram that stops parsing keeps its last good rendering plus',
    'a short note, so nothing disappears while you type.',
    '',
    '`Insert → Kanban Board…` (or the toolbar\'s **Kanban** button) starts a new',
    'board: name the columns, one per line, `Ctrl+Enter` to add it. It arrives',
    'open in edit mode, so the **+** can fill it.',
    '',
    'Right-click the diagram for Copy as image / Save as image.',
    '',
    '## Runnable code blocks',
    '',
    'A fenced code block whose first line is a shebang becomes runnable:',
    '',
    '````',
    '```python',
    '#!/usr/bin/env python3',
    'print("Hello from Edi!")',
    '```',
    '````',
    '',
    'The preview shows a **Run** button; output lands beneath the block and',
    '**Stop** cancels a hung run.',
    '',
    '## Export',
    '',
    '`Ctrl+Shift+E` exports the rendered preview — Mermaid diagrams, computed',
    'spreadsheet values, and code output included — as one self-contained HTML',
    'file you can share or archive.',
    '',
  ].join('\n')
}